export type AgentId = string;
export type TeamId = string;
export type ChannelId = string;
export type MessageId = string;
export type CorrelationId = string;
export type BindingId = string;
export type OperationId = string;

export interface AgentRecord {
  readonly agentId: AgentId;
  readonly displayName: string | null;
  readonly lifecycle: "active" | "retired";
  readonly createdAt: string;
  readonly updatedAt: string;
}

export interface TeamMember {
  readonly teamId: TeamId;
  readonly agentId: AgentId;
  readonly role: string;
  /** Team-scoped hierarchy. It is not global command authority. */
  readonly parentAgentId: AgentId | null;
  readonly joinedAt: string;
  readonly updatedAt: string;
}

export interface TeamRecord {
  readonly teamId: TeamId;
  readonly displayName: string | null;
  readonly createdAt: string;
  readonly members: readonly TeamMember[];
}

export interface ChannelRecord {
  readonly channelId: ChannelId;
  readonly displayName: string | null;
  readonly teamId: TeamId | null;
  readonly leadAgentId: AgentId | null;
  readonly createdAt: string;
  readonly memberAgentIds: readonly AgentId[];
}

export type MessageClass =
  | "request"
  | "informational"
  | "completion"
  | "steering"
  | "reaction"
  | "system";

export type MessageTarget =
  | { readonly type: "agent"; readonly id: AgentId }
  | { readonly type: "channel"; readonly id: ChannelId };

export type ProvenanceSource = "http" | "mcp" | "t3" | "internal";

/** Generated by a trusted transport. Message content never alters it. */
export interface MessageProvenance {
  readonly authenticatedPrincipalId: string;
  readonly source: ProvenanceSource;
  readonly sourceInstanceId: string | null;
  readonly sourceOperationId: string | null;
  readonly trust: "untrusted";
}

export interface MessageRecord {
  readonly messageId: MessageId;
  readonly idempotencyKey: string;
  readonly fromAgentId: AgentId;
  readonly target: MessageTarget;
  readonly correlationId: CorrelationId;
  readonly body: string;
  readonly messageClass: MessageClass;
  readonly metadata: Readonly<Record<string, unknown>>;
  readonly provenance: MessageProvenance;
  readonly createdAt: string;
  readonly recipientAgentIds: readonly AgentId[];
}

export type DeliveryStatus = "pending" | "claimed" | "delivered" | "dead_letter";

/** @deprecated Host-operation progress is separate from mailbox delivery. */
export type DeliveryStage =
  | "queued"
  | "dispatching"
  | "accepted"
  | "adopted"
  | "observed"
  | "failed"
  | "indeterminate";

export interface DeliveryRecord {
  readonly messageId: MessageId;
  readonly recipientAgentId: AgentId;
  readonly status: DeliveryStatus;
  readonly consumerId: string | null;
  readonly claimExpiresAt: string | null;
  readonly receiptId: string | null;
  readonly deliveredAt: string | null;
}

/** The raw claim token is returned once and is never part of DeliveryRecord. */
export interface ClaimRecord extends DeliveryRecord {
  readonly status: "claimed";
  readonly consumerId: string;
  readonly claimToken: string;
  readonly claimExpiresAt: string;
}

export type BindingState = "starting" | "running" | "idle" | "stopped" | "failed" | "unknown";

export interface AgentBinding {
  readonly bindingId: BindingId;
  readonly agentId: AgentId;
  readonly adapter: string;
  readonly hostInstanceId: string;
  readonly externalId: string;
  readonly providerSessionId: string | null;
  readonly generation: number;
  readonly state: BindingState;
  readonly active: boolean;
  readonly capabilities: Readonly<Record<string, boolean>>;
  readonly metadata: Readonly<Record<string, unknown>>;
  readonly leaseExpiresAt: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
}

export type HostOperationKind = "spawn" | "bind" | "send" | "interrupt" | "stop";
export type HostOperationStage = DeliveryStage;

export interface OperationRecord {
  readonly operationId: OperationId;
  readonly principalId: string;
  readonly idempotencyKey: string;
  readonly requestHash: string;
  readonly kind: HostOperationKind;
  readonly adapter: string;
  readonly agentId: AgentId;
  readonly bindingId: BindingId | null;
  readonly messageId: MessageId | null;
  readonly correlationId: CorrelationId | null;
  readonly stage: HostOperationStage;
  readonly dispatchOwnerId: string | null;
  readonly dispatchStartedAt: string | null;
  readonly hostReceiptId: string | null;
  readonly detail: Readonly<Record<string, unknown>>;
  readonly errorCode: string | null;
  readonly errorMessage: string | null;
  readonly createdAt: string;
  readonly updatedAt: string;
}

export interface SidebandEvent {
  readonly schemaVersion: 1;
  readonly sequence: number;
  readonly eventId: string;
  readonly type: string;
  readonly entityType: string;
  readonly entityId: string;
  readonly actorPrincipalId: string;
  readonly correlationId: string | null;
  readonly causationId: string | null;
  readonly payload: Readonly<Record<string, unknown>>;
  readonly occurredAt: string;
}

export interface PresenceRecord {
  readonly agentId: AgentId;
  readonly state: "online" | "idle" | "offline" | "never_seen";
  readonly lastSeenAt: string | null;
  readonly lastSignal: string | null;
}

export interface PageRequest {
  readonly after?: string;
  readonly limit?: number;
}

export interface Page<T> {
  readonly items: readonly T[];
  readonly next: string | null;
}
